version in ThisBuild := "1.16"
//version in ThisBuild := "1.8"
// version in ThisBuild := "1.4"
// version in ThisBuild := "1.2"
// version in ThisBuild := "1.0"
// version in ThisBuild := "2.0"
// version in ThisBuild := "4.0"
